const S = require('../../../test/utils/settings.js');
const E = require('../../enums');

exports.generate_PUT_request_payload_for_Editing_Auto_Disposition = function
    (enable) {

    let body = {
        "isAutoDispositionOn": enable,
        "officeAutoDispositionReviewers": [{
            "officeId": 135,
            "officeName": "Cypress Office1",
            "generalTaskFromUserId": null,
            "generalTaskFromUserGroupId": 95,
            "isDefault": true,
            "isGeneralTaskFromUser": false
        }, {
            "officeId": 137,
            "officeName": "Cypress Office2",
            "generalTaskFromUserId": null,
            "generalTaskFromUserGroupId": 95,
            "isDefault": false,
            "isGeneralTaskFromUser": false
        }],
        "settings": [{
            "id": 246,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 1,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 1,
                "name": "Other",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 247,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 2,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 2,
                "name": "Arson",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 248,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 3,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 3,
                "name": "Assault",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 249,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 4,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 4,
                "name": "Burglary",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 250,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 5,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 5,
                "name": "Child Abuse",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 251,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 6,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 6,
                "name": "Child Pornography",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 252,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 7,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 7,
                "name": "Computer Crime",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 253,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 8,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 8,
                "name": "Criminal Mischief",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 254,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 9,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 9,
                "name": "Disorderly Conduct",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 255,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 10,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 10,
                "name": "Domestic Violence",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 256,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 11,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 11,
                "name": "Drug Offense",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 257,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 12,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 12,
                "name": "Drunk Driving",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 258,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 13,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 13,
                "name": "Embezzlement",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 259,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 14,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 14,
                "name": "Forgery",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 260,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 15,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 15,
                "name": "Found Property",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 261,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 16,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 16,
                "name": "Fraud",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 262,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 17,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 17,
                "name": "Harassment",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 263,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 18,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 18,
                "name": "Identity Theft",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 264,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 19,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 19,
                "name": "Kidnapping",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 265,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 20,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 20,
                "name": "Homicide / Murder",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 266,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 21,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 21,
                "name": "Public Intoxication",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 267,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 22,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 22,
                "name": "Receiving Stolen Property",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 268,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 23,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 23,
                "name": "Robbery",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 269,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 24,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 24,
                "name": "Sexual Assault",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 270,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 25,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 25,
                "name": "Solicitation / Prostitution",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 271,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 26,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 26,
                "name": "Stalking",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 272,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 27,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 27,
                "name": "Theft",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 273,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 28,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 28,
                "name": "Vandalism",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 274,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 29,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 29,
                "name": "Unknown",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 275,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 30,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 30,
                "name": "Litigation",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 276,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 31,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 31,
                "name": "Litigation Hold",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 277,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 32,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 32,
                "name": "Investigation",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 278,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 33,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 33,
                "name": "Lock",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 279,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 38,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 38,
                "name": "Incident",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 280,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 39,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 39,
                "name": "Forensic Investigation",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 281,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 40,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 40,
                "name": "Manager Request for Data",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 282,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 42,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 42,
                "name": "Shootings",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 283,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 43,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 43,
                "name": "Death Investigation",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 284,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 44,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 44,
                "name": "Traffic",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 285,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 46,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 46,
                "name": "Weapons Charge",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 286,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 47,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 47,
                "name": "Alcohol Related",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 287,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 48,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 48,
                "name": "Battery",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 288,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 49,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 49,
                "name": "Trespass",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 289,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 50,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 50,
                "name": "Suspicious Activity",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 290,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 51,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 51,
                "name": "Conservation Violation",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 291,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 52,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 52,
                "name": "Manslaughter",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 292,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 53,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 53,
                "name": "DUI / DWI",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 293,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 54,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 54,
                "name": "DUII",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 294,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 55,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 55,
                "name": "Threatening",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 295,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 56,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 56,
                "name": "Divorce",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 296,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 57,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 57,
                "name": "Custody",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 297,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 58,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 58,
                "name": "Adoption",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 298,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 59,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 59,
                "name": "Civil",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 299,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 60,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 60,
                "name": "Criminal",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 300,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 62,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 62,
                "name": "Employment",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 301,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 63,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 63,
                "name": "Landlord / Tenant",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 302,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 64,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 64,
                "name": "Real Estate",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 303,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 65,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 65,
                "name": "SearchOne",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 304,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 66,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 66,
                "name": "Settlements",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 305,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 67,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 67,
                "name": "Stabbing",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 306,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 68,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 68,
                "name": "Forensic Accounting",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 307,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 69,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 69,
                "name": "E - Discovery",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 308,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 70,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 70,
                "name": "Non Specific",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 309,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 71,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 71,
                "name": "Business Valuation",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 310,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 72,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 72,
                "name": "Injured Person",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 311,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 73,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 73,
                "name": "Obstructing",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 312,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 74,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 74,
                "name": "F.P.O.",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 313,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 75,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 75,
                "name": "Prohibited Possession",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 314,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 76,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 76,
                "name": "B & E",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 315,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 77,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 77,
                "name": "D.O.P.",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 316,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 78,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 78,
                "name": "Animal Cruelty",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 317,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 79,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 79,
                "name": "Crash / Accident",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 318,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 80,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 80,
                "name": "Hit & Run / Leaving the Scene",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 319,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 81,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 81,
                "name": "Contributing to a Minor",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 320,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 82,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 82,
                "name": "Counterfeiting",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 321,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 83,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 83,
                "name": "Forgery / Uttering",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 322,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 85,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 85,
                "name": "Cyber Security",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 323,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 86,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 86,
                "name": "Assessment",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 324,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 87,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 87,
                "name": "Warrant",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 325,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 88,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 88,
                "name": "F.P.O. Violation",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 326,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 89,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 89,
                "name": "Carrying Concealed Weapon",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 327,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 90,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 90,
                "name": "School Offense",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 328,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 91,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 91,
                "name": "Animal Abuse - I (intentional abuse/torture)",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 329,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 92,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 92,
                "name": "Animal Abuse - S (animal sex abuse)",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 330,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 93,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 93,
                "name": "Animal Abuse - F (animal fighting)",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 331,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 94,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 94,
                "name": "Animal Hoarding",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 332,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 95,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 95,
                "name": "Death Investigation - Accidental",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 333,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 96,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 96,
                "name": "Death Investigation - Natural",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 334,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 97,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 97,
                "name": "Death Investigation - Undetermined",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 335,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 98,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 98,
                "name": "Hyperthermia - Hot Car",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 336,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 99,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 99,
                "name": "Hypothermia - Cold Car",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 337,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 100,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 100,
                "name": "Starvation",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 338,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 101,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 101,
                "name": "Failure to provide veterinary care",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 339,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 102,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 102,
                "name": "Failure to provide water",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 340,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 103,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 103,
                "name": "Failure to provide necessary grooming",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 341,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 104,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 104,
                "name": "Intellectual Property Theft",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 342,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 105,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 105,
                "name": "Criminal Damage",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 343,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 106,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 106,
                "name": "Retail Theft",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 344,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 107,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 107,
                "name": "Gambling",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 345,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 108,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 108,
                "name": "Overdose",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 346,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 109,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 109,
                "name": "Drug Offense - Civil",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 347,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 110,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 110,
                "name": "Tampering with MV",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 348,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 111,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 111,
                "name": "Assist Other Agency",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 349,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 112,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 112,
                "name": "Littering / Dumping",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 350,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 113,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 113,
                "name": "Drug Drop Box",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 351,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 114,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 114,
                "name": "Negligent Use - Firearm",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 352,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 115,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 115,
                "name": "Injuring / Tampering w/ Motor Vehicle",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 353,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 116,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 116,
                "name": "Family Violence",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 354,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 117,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 117,
                "name": "Explosives",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 355,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 118,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 118,
                "name": "Drug Paraphernalia",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 356,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 119,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 119,
                "name": "Pending",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 357,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 120,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 120,
                "name": "Natural",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 358,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 121,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 121,
                "name": "Accident",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 359,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 122,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 122,
                "name": "Suicide",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 360,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 123,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 123,
                "name": "Undetermined",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 361,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 124,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 124,
                "name": "Resisting/Evading/Obstructing a Police Officer",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }, {
            "id": 362,
            "active": true,
            "daysToFollowUp": 1,
            "organizationId": 23,
            "organization": null,
            "offenseTypeId": 125,
            "offenseType": {
                "organizationOffenseTypeFollowUpDays": null,
                "id": 125,
                "name": "Suicide Attempt",
                "active": true,
                "offenseTypeForms": null,
                "organizations": [],
                "autoDispositionSettings": [],
                "customDropdownCategoryId": 1,
                "customDropdownCategory": null
            }
        }],
        "listPermissionGroupIds": [213, 214],
        "createPermissionGroupIds": [214],
        "updatePermissionGroupIds": [214],
        "generalTaskFromUserGroupId": null
    };
    return body;
};
